services:
  app:
    build: .
    env_file: .env  
    ports:
      - "8000:8000"
    depends_on:
      - redis  

  redis:
    image: redis:alpine 
    ports:
      - "6380:6380"
    volumes:
      - redis_data:/data  

volumes:
  redis_data:  